### ISSUE TITLE
Link on QuantLib web site

### ISSUE THREAD

**Issue by lballabio** [sthabene/QuantIO#1]
Hello, please let me know if you want me to add a link to your project to the QuantLib web site (we maintain a list of extensions at https://www.quantlib.org/extensions.shtml).  And good luck with the project!

**Comment by sthabene** [comment]
Hi Luigi, thanks for reaching out. Yes, you can add the project, that would be great. However, I must point out that at this moment, it is still a work in progress. It is a passion project, and I only to get work on it when I have time, but I do have plans to develop it further, to a point where one can at least fully price and gets risk measures for one financial product. Thanks!

**Comment by lballabio** [comment]
Done — good luck again!
